apiVersion: v1
kind: Service
metadata:
  name: {{ template "template.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "template.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
    type: deployment
spec:
  ports:
    - name: server
      port: {PORT}
      protocol: TCP
      targetPort: {PORT}
  selector:
    app.kubernetes.io/name: {{ template "template.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
    type: deployment
